<?php

// Data functions (insert, update, delete, form) for table orders

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function orders_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('orders');
	if(!$arrPerm['insert']) return false;

	$data = [
		'CustomerID' => Request::lookup('CustomerID', ''),
		'EmployeeID' => Request::lookup('EmployeeID', ''),
		'OrderDate' => Request::dateComponents('OrderDate', '1'),
		'OrderTime' => time24(Request::val('OrderTime', '')),
		'RequiredDate' => Request::dateComponents('RequiredDate', '1'),
		'ShippedDate' => Request::dateComponents('ShippedDate', ''),
		'ShipVia' => Request::lookup('ShipVia', 'Federal Shipping'),
		'Freight' => Request::val('Freight', '0'),
		'ShipName' => Request::lookup('CustomerID'),
		'ShipAddress' => Request::lookup('CustomerID'),
		'ShipCity' => Request::lookup('CustomerID'),
		'ShipRegion' => Request::lookup('CustomerID'),
		'ShipPostalCode' => Request::lookup('CustomerID'),
		'ShipCountry' => Request::lookup('CustomerID'),
		'added_by' => parseCode('<%%creatorUsername%%>', true),
		'added_date' => parseCode('<%%creationDate%%>', true, true),
	];


	// hook: orders_before_insert
	if(function_exists('orders_before_insert')) {
		$args = [];
		if(!orders_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('orders', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('orders', $recID, calculated_fields()['orders']);

	// hook: orders_after_insert
	if(function_exists('orders_after_insert')) {
		$res = sql("SELECT * FROM `orders` WHERE `OrderID`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!orders_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	// record owner is current user
	$recordOwner = getLoggedMemberID();
	set_record_owner('orders', $recID, $recordOwner);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) orders_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function orders_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function orders_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('orders', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: orders_before_delete
	if(function_exists('orders_before_delete')) {
		$args = [];
		if(!orders_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: order_details
	$res = sql("SELECT `OrderID` FROM `orders` WHERE `OrderID`='{$selected_id}'", $eo);
	$OrderID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `order_details` WHERE `OrderID`='" . makeSafe($OrderID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="order_details_view.php?filterer_OrderID=' . urlencode($OrderID[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'order_details'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'order_details'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'orders_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'orders_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `orders` WHERE `OrderID`='{$selected_id}'", $eo);

	// hook: orders_after_delete
	if(function_exists('orders_after_delete')) {
		$args = [];
		orders_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='orders' AND `pkValue`='{$selected_id}'", $eo);
}

function orders_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('orders', $selected_id, 'edit')) return false;

	$data = [
		'CustomerID' => Request::lookup('CustomerID', ''),
		'EmployeeID' => Request::lookup('EmployeeID', ''),
		'OrderDate' => Request::dateComponents('OrderDate', ''),
		'OrderTime' => time24(Request::val('OrderTime', '')),
		'RequiredDate' => Request::dateComponents('RequiredDate', ''),
		'ShippedDate' => Request::dateComponents('ShippedDate', ''),
		'ShipVia' => Request::lookup('ShipVia', ''),
		'Freight' => Request::val('Freight', ''),
		'ShipName' => Request::lookup('CustomerID'),
		'ShipAddress' => Request::lookup('CustomerID'),
		'ShipCity' => Request::lookup('CustomerID'),
		'ShipRegion' => Request::lookup('CustomerID'),
		'ShipPostalCode' => Request::lookup('CustomerID'),
		'ShipCountry' => Request::lookup('CustomerID'),
	];

	// get existing values
	$old_data = getRecord('orders', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: orders_before_update
	if(function_exists('orders_before_update')) {
		$args = ['old_data' => $old_data];
		if(!orders_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'orders', 
		backtick_keys_once($set), 
		['`OrderID`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="orders_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('orders', $data['selectedID'], calculated_fields()['orders']);

	// hook: orders_after_update
	if(function_exists('orders_after_update')) {
		$res = sql("SELECT * FROM `orders` WHERE `OrderID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['OrderID'];
		$args = ['old_data' => $old_data];
		if(!orders_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('orders', $selected_id);
}

function orders_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('orders');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('orders', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('orders', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('orders', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_CustomerID = Request::val('filterer_CustomerID');
	$filterer_EmployeeID = Request::val('filterer_EmployeeID');
	$filterer_ShipVia = Request::val('filterer_ShipVia');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: CustomerID
	$combo_CustomerID = new DataCombo;
	// combobox: EmployeeID
	$combo_EmployeeID = new DataCombo;
	// combobox: OrderDate
	$combo_OrderDate = new DateCombo;
	$combo_OrderDate->DateFormat = "mdy";
	$combo_OrderDate->MinYear = defined('orders.OrderDate.MinYear') ? constant('orders.OrderDate.MinYear') : 1900;
	$combo_OrderDate->MaxYear = defined('orders.OrderDate.MaxYear') ? constant('orders.OrderDate.MaxYear') : 2100;
	$combo_OrderDate->DefaultDate = parseMySQLDate('1', '1');
	$combo_OrderDate->MonthNames = $Translation['month names'];
	$combo_OrderDate->NamePrefix = 'OrderDate';
	// combobox: RequiredDate
	$combo_RequiredDate = new DateCombo;
	$combo_RequiredDate->DateFormat = "mdy";
	$combo_RequiredDate->MinYear = defined('orders.RequiredDate.MinYear') ? constant('orders.RequiredDate.MinYear') : 1900;
	$combo_RequiredDate->MaxYear = defined('orders.RequiredDate.MaxYear') ? constant('orders.RequiredDate.MaxYear') : 2100;
	$combo_RequiredDate->DefaultDate = parseMySQLDate('1', '1');
	$combo_RequiredDate->MonthNames = $Translation['month names'];
	$combo_RequiredDate->NamePrefix = 'RequiredDate';
	// combobox: ShippedDate
	$combo_ShippedDate = new DateCombo;
	$combo_ShippedDate->DateFormat = "mdy";
	$combo_ShippedDate->MinYear = defined('orders.ShippedDate.MinYear') ? constant('orders.ShippedDate.MinYear') : 1900;
	$combo_ShippedDate->MaxYear = defined('orders.ShippedDate.MaxYear') ? constant('orders.ShippedDate.MaxYear') : 2100;
	$combo_ShippedDate->DefaultDate = parseMySQLDate('', '');
	$combo_ShippedDate->MonthNames = $Translation['month names'];
	$combo_ShippedDate->NamePrefix = 'ShippedDate';
	// combobox: ShipVia
	$combo_ShipVia = new DataCombo;
	// combobox: added_date
	$combo_added_date = new DateCombo;
	$combo_added_date->DateFormat = "mdy";
	$combo_added_date->MinYear = defined('orders.added_date.MinYear') ? constant('orders.added_date.MinYear') : 1900;
	$combo_added_date->MaxYear = defined('orders.added_date.MaxYear') ? constant('orders.added_date.MaxYear') : 2100;
	$combo_added_date->DefaultDate = parseMySQLDate('<%%creationDate%%>', '<%%creationDate%%>');
	$combo_added_date->MonthNames = $Translation['month names'];
	$combo_added_date->NamePrefix = 'added_date';

	if($hasSelectedId) {
		$res = sql("SELECT * FROM `orders` WHERE `OrderID`='" . makeSafe($selectedId) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'orders_view.php', false);
		}
		$combo_CustomerID->SelectedData = $row['CustomerID'];
		$combo_EmployeeID->SelectedData = $row['EmployeeID'];
		$combo_OrderDate->DefaultDate = $row['OrderDate'];
		$combo_RequiredDate->DefaultDate = $row['RequiredDate'];
		$combo_ShippedDate->DefaultDate = $row['ShippedDate'];
		$combo_ShipVia->SelectedData = $row['ShipVia'];
		$combo_added_date->DefaultDate = $row['added_date'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_CustomerID->SelectedData = $filterer_CustomerID;
		$combo_EmployeeID->SelectedData = $filterer_EmployeeID;
		$combo_ShipVia->SelectedData = $filterer_ShipVia;
	}
	$combo_CustomerID->HTML = '<span id="CustomerID-container' . $rnd1 . '"></span><input type="hidden" name="CustomerID" id="CustomerID' . $rnd1 . '" value="' . html_attr($combo_CustomerID->SelectedData) . '">';
	$combo_CustomerID->MatchText = '<span id="CustomerID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="CustomerID" id="CustomerID' . $rnd1 . '" value="' . html_attr($combo_CustomerID->SelectedData) . '">';
	$combo_EmployeeID->HTML = '<span id="EmployeeID-container' . $rnd1 . '"></span><input type="hidden" name="EmployeeID" id="EmployeeID' . $rnd1 . '" value="' . html_attr($combo_EmployeeID->SelectedData) . '">';
	$combo_EmployeeID->MatchText = '<span id="EmployeeID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="EmployeeID" id="EmployeeID' . $rnd1 . '" value="' . html_attr($combo_EmployeeID->SelectedData) . '">';
	$combo_ShipVia->HTML = '<span id="ShipVia-container' . $rnd1 . '"></span><input type="hidden" name="ShipVia" id="ShipVia' . $rnd1 . '" value="' . html_attr($combo_ShipVia->SelectedData) . '">';
	$combo_ShipVia->MatchText = '<span id="ShipVia-container-readonly' . $rnd1 . '"></span><input type="hidden" name="ShipVia" id="ShipVia' . $rnd1 . '" value="' . html_attr($combo_ShipVia->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_CustomerID__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['CustomerID'] : htmlspecialchars($filterer_CustomerID, ENT_QUOTES)); ?>"};
		AppGini.current_EmployeeID__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['EmployeeID'] : htmlspecialchars($filterer_EmployeeID, ENT_QUOTES)); ?>"};
		AppGini.current_ShipVia__RAND__ = { text: "<?php echo ($hasSelectedId ? '' : 'Federal Shipping'); ?>", value: "<?php echo addslashes($hasSelectedId ? $urow['ShipVia'] : htmlspecialchars($filterer_ShipVia, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(CustomerID_reload__RAND__) == 'function') CustomerID_reload__RAND__();
				if(typeof(EmployeeID_reload__RAND__) == 'function') EmployeeID_reload__RAND__();
				if(typeof(ShipVia_reload__RAND__) == 'function') ShipVia_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function CustomerID_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#CustomerID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_CustomerID__RAND__.value, t: 'orders', f: 'CustomerID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="CustomerID"]').val(resp.results[0].id);
							$j('[id=CustomerID-container-readonly__RAND__]').html('<span class="match-text" id="CustomerID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=customers_view_parent]').hide(); } else { $j('.btn[id=customers_view_parent]').show(); }


							if(typeof(CustomerID_update_autofills__RAND__) == 'function') CustomerID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'orders', f: 'CustomerID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_CustomerID__RAND__.value = e.added.id;
				AppGini.current_CustomerID__RAND__.text = e.added.text;
				$j('[name="CustomerID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=customers_view_parent]').hide(); } else { $j('.btn[id=customers_view_parent]').show(); }


				if(typeof(CustomerID_update_autofills__RAND__) == 'function') CustomerID_update_autofills__RAND__();
			});

			if(!$j("#CustomerID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_CustomerID__RAND__.value, t: 'orders', f: 'CustomerID' },
					success: function(resp) {
						$j('[name="CustomerID"]').val(resp.results[0].id);
						$j('[id=CustomerID-container-readonly__RAND__]').html('<span class="match-text" id="CustomerID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=customers_view_parent]').hide(); } else { $j('.btn[id=customers_view_parent]').show(); }

						if(typeof(CustomerID_update_autofills__RAND__) == 'function') CustomerID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_CustomerID__RAND__.value, t: 'orders', f: 'CustomerID' },
				success: function(resp) {
					$j('[id=CustomerID-container__RAND__], [id=CustomerID-container-readonly__RAND__]').html('<span class="match-text" id="CustomerID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=customers_view_parent]').hide(); } else { $j('.btn[id=customers_view_parent]').show(); }

					if(typeof(CustomerID_update_autofills__RAND__) == 'function') CustomerID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function EmployeeID_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#EmployeeID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_EmployeeID__RAND__.value, t: 'orders', f: 'EmployeeID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="EmployeeID"]').val(resp.results[0].id);
							$j('[id=EmployeeID-container-readonly__RAND__]').html('<span class="match-text" id="EmployeeID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=employees_view_parent]').hide(); } else { $j('.btn[id=employees_view_parent]').show(); }


							if(typeof(EmployeeID_update_autofills__RAND__) == 'function') EmployeeID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'orders', f: 'EmployeeID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_EmployeeID__RAND__.value = e.added.id;
				AppGini.current_EmployeeID__RAND__.text = e.added.text;
				$j('[name="EmployeeID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=employees_view_parent]').hide(); } else { $j('.btn[id=employees_view_parent]').show(); }


				if(typeof(EmployeeID_update_autofills__RAND__) == 'function') EmployeeID_update_autofills__RAND__();
			});

			if(!$j("#EmployeeID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_EmployeeID__RAND__.value, t: 'orders', f: 'EmployeeID' },
					success: function(resp) {
						$j('[name="EmployeeID"]').val(resp.results[0].id);
						$j('[id=EmployeeID-container-readonly__RAND__]').html('<span class="match-text" id="EmployeeID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=employees_view_parent]').hide(); } else { $j('.btn[id=employees_view_parent]').show(); }

						if(typeof(EmployeeID_update_autofills__RAND__) == 'function') EmployeeID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_EmployeeID__RAND__.value, t: 'orders', f: 'EmployeeID' },
				success: function(resp) {
					$j('[id=EmployeeID-container__RAND__], [id=EmployeeID-container-readonly__RAND__]').html('<span class="match-text" id="EmployeeID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=employees_view_parent]').hide(); } else { $j('.btn[id=employees_view_parent]').show(); }

					if(typeof(EmployeeID_update_autofills__RAND__) == 'function') EmployeeID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function ShipVia_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#ShipVia-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						<?php if(!$hasSelectedId && !$filterer_ShipVia) { ?>
							data: { text: AppGini.htmlEntitiesToText('Federal Shipping'), t: 'orders', f: 'ShipVia' },
						<?php } else { ?>
							data: { id: AppGini.current_ShipVia__RAND__.value, t: 'orders', f: 'ShipVia' },
						<?php } ?>

						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="ShipVia"]').val(resp.results[0].id);
							$j('[id=ShipVia-container-readonly__RAND__]').html('<span class="match-text" id="ShipVia-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=shippers_view_parent]').hide(); } else { $j('.btn[id=shippers_view_parent]').show(); }


							if(typeof(ShipVia_update_autofills__RAND__) == 'function') ShipVia_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'orders', f: 'ShipVia' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_ShipVia__RAND__.value = e.added.id;
				AppGini.current_ShipVia__RAND__.text = e.added.text;
				$j('[name="ShipVia"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=shippers_view_parent]').hide(); } else { $j('.btn[id=shippers_view_parent]').show(); }


				if(typeof(ShipVia_update_autofills__RAND__) == 'function') ShipVia_update_autofills__RAND__();
			});

			if(!$j("#ShipVia-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_ShipVia__RAND__.value, t: 'orders', f: 'ShipVia' },
					success: function(resp) {
						$j('[name="ShipVia"]').val(resp.results[0].id);
						$j('[id=ShipVia-container-readonly__RAND__]').html('<span class="match-text" id="ShipVia-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=shippers_view_parent]').hide(); } else { $j('.btn[id=shippers_view_parent]').show(); }

						if(typeof(ShipVia_update_autofills__RAND__) == 'function') ShipVia_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_ShipVia__RAND__.value, t: 'orders', f: 'ShipVia' },
				success: function(resp) {
					$j('[id=ShipVia-container__RAND__], [id=ShipVia-container-readonly__RAND__]').html('<span class="match-text" id="ShipVia-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=shippers_view_parent]').hide(); } else { $j('.btn[id=shippers_view_parent]').show(); }

					if(typeof(ShipVia_update_autofills__RAND__) == 'function') ShipVia_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/orders_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/orders_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detail View', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#CustomerID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#CustomerID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#EmployeeID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#EmployeeID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#OrderDate').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#OrderDateDay, #OrderDateMonth, #OrderDateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#OrderTime').replaceWith('<div class=\"form-control-static\" id=\"OrderTime\">' + (jQuery('#OrderTime').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#RequiredDate').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#RequiredDateDay, #RequiredDateMonth, #RequiredDateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ShippedDate').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#ShippedDateDay, #ShippedDateMonth, #ShippedDateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ShipVia').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#ShipVia_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Freight').replaceWith('<div class=\"form-control-static\" id=\"Freight\">' + (jQuery('#Freight').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\tjQuery('#OrderTime').addClass('always_shown').timepicker({ defaultTime: false, showSeconds: true, showMeridian: true, showInputs: false, disableFocus: true, minuteStep: 5 });";
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(CustomerID)%%>', $combo_CustomerID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(CustomerID)%%>', $combo_CustomerID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(CustomerID)%%>', urlencode($combo_CustomerID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(EmployeeID)%%>', $combo_EmployeeID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(EmployeeID)%%>', $combo_EmployeeID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(EmployeeID)%%>', urlencode($combo_EmployeeID->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(OrderDate)%%>', 
		(!$fieldsAreEditable ? 
			'<div class="form-control-static">' . $combo_OrderDate->GetHTML(true) . '</div>' : 
			$combo_OrderDate->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(OrderDate)%%>', $combo_OrderDate->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(RequiredDate)%%>', 
		(!$fieldsAreEditable ? 
			'<div class="form-control-static">' . $combo_RequiredDate->GetHTML(true) . '</div>' : 
			$combo_RequiredDate->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(RequiredDate)%%>', $combo_RequiredDate->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(ShippedDate)%%>', 
		(!$fieldsAreEditable ? 
			'<div class="form-control-static">' . $combo_ShippedDate->GetHTML(true) . '</div>' : 
			$combo_ShippedDate->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ShippedDate)%%>', $combo_ShippedDate->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(ShipVia)%%>', $combo_ShipVia->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ShipVia)%%>', $combo_ShipVia->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(ShipVia)%%>', urlencode($combo_ShipVia->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(added_date)%%>', 
		(!$fieldsAreEditable ? 
			'<div class="form-control-static">' . $combo_added_date->GetHTML(true) . '</div>' : 
			$combo_added_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(added_date)%%>', $combo_added_date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['CustomerID' => ['customers', 'Customer'], 'EmployeeID' => ['employees', 'Employee'], 'ShipVia' => ['shippers', 'Ship Via'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(OrderID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CustomerID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(EmployeeID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(OrderDate)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(OrderTime)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(RequiredDate)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ShippedDate)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ShipVia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Freight)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(added_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(added_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Total)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(OrderID)%%>', safe_html($urow['OrderID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(OrderID)%%>', html_attr($row['OrderID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(OrderID)%%>', urlencode($urow['OrderID']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Status)%%>', safe_html($urow['Status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Status)%%>', urlencode($urow['Status']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CustomerID)%%>', safe_html($urow['CustomerID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CustomerID)%%>', html_attr($row['CustomerID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CustomerID)%%>', urlencode($urow['CustomerID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(EmployeeID)%%>', safe_html($urow['EmployeeID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(EmployeeID)%%>', html_attr($row['EmployeeID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(EmployeeID)%%>', urlencode($urow['EmployeeID']), $templateCode);
		$templateCode = str_replace('<%%VALUE(OrderDate)%%>', app_datetime($row['OrderDate']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(OrderDate)%%>', urlencode(app_datetime($urow['OrderDate'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(OrderTime)%%>', time12(html_attr($row['OrderTime'])), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(OrderTime)%%>', urlencode(time12($urow['OrderTime'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(RequiredDate)%%>', app_datetime($row['RequiredDate']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(RequiredDate)%%>', urlencode(app_datetime($urow['RequiredDate'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(ShippedDate)%%>', app_datetime($row['ShippedDate']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ShippedDate)%%>', urlencode(app_datetime($urow['ShippedDate'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ShipVia)%%>', safe_html($urow['ShipVia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ShipVia)%%>', html_attr($row['ShipVia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ShipVia)%%>', urlencode($urow['ShipVia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Freight)%%>', safe_html($urow['Freight']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Freight)%%>', html_attr($row['Freight']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Freight)%%>', urlencode($urow['Freight']), $templateCode);
		$templateCode = str_replace('<%%VALUE(added_by)%%>', safe_html($urow['added_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(added_by)%%>', urlencode($urow['added_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(added_date)%%>', app_datetime($row['added_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(added_date)%%>', urlencode(app_datetime($urow['added_date'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(Total)%%>', safe_html($urow['Total']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Total)%%>', urlencode($urow['Total']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(OrderID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(OrderID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Status)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Status)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CustomerID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CustomerID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(EmployeeID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(EmployeeID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(OrderDate)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(OrderDate)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(OrderTime)%%>', time12(''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(OrderTime)%%>', urlencode(time12('')), $templateCode);
		$templateCode = str_replace('<%%VALUE(RequiredDate)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(RequiredDate)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(ShippedDate)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ShippedDate)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ShipVia)%%>', 'Federal Shipping', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ShipVia)%%>', urlencode('Federal Shipping'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Freight)%%>', '0', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Freight)%%>', urlencode('0'), $templateCode);
		$templateCode = str_replace('<%%VALUE(added_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(added_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(added_date)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(added_date)%%>', urlencode('<%%creationDate%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Total)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Total)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tCustomerID_update_autofills$rnd1 = function() {\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint) {
		$templateCode .= "\t\t\turl: 'orders_autofill.php?rnd1=$rnd1&mfk=CustomerID&id=' + encodeURIComponent('".addslashes($row['CustomerID'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET'\n";
	} else {
		$templateCode .= "\t\t\turl: 'orders_autofill.php?rnd1=$rnd1&mfk=CustomerID&id=' + encodeURIComponent(AppGini.current_CustomerID{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "',\n";
		$templateCode .= "\t\t\ttype: 'GET',\n";
		$templateCode .= "\t\t\tbeforeSend: function() { \$j('#CustomerID$rnd1').prop('disabled', true); },\n";
		$templateCode .= "\t\t\tcomplete: function() { " . (($allowInsert || $allowUpdate) ? "\$j('#CustomerID$rnd1').prop('disabled', false); " : "\$j('#CustomerID$rnd1').prop('disabled', true); ")." \$j(window).resize(); }\n";
	}
	$templateCode .= "\t\t});\n";
	$templateCode .= "\t};\n";
	if(!$dvprint) $templateCode .= "\tif(\$j('#CustomerID_caption').length) \$j('#CustomerID_caption').click(function() { CustomerID_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('orders');
	if($hasSelectedId) {
		$jdata = get_joined_record('orders', $selectedId);
		if($jdata === false) $jdata = get_defaults('orders');
		$rdata = $row;
	}
	$templateCode .= loadView('orders-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: orders_dv
	if(function_exists('orders_dv')) {
		$args = [];
		orders_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}