<?php
// This script and data application were generated by AppGini 5.92
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/shippers.php");
	include_once("{$currDir}/shippers_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('shippers');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = 'shippers';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`shippers`.`ShipperID`" => "ShipperID",
		"`shippers`.`CompanyName`" => "CompanyName",
		"`shippers`.`Phone`" => "Phone",
		"`shippers`.`NumOrders`" => "NumOrders",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`shippers`.`ShipperID`',
		2 => 2,
		3 => 3,
		4 => '`shippers`.`NumOrders`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`shippers`.`ShipperID`" => "ShipperID",
		"`shippers`.`CompanyName`" => "CompanyName",
		"`shippers`.`Phone`" => "Phone",
		"`shippers`.`NumOrders`" => "NumOrders",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`shippers`.`ShipperID`" => "Shipper ID",
		"`shippers`.`CompanyName`" => "Company Name",
		"`shippers`.`Phone`" => "Phone",
		"`shippers`.`NumOrders`" => "Number of orders shipped",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`shippers`.`ShipperID`" => "ShipperID",
		"`shippers`.`CompanyName`" => "CompanyName",
		"`shippers`.`Phone`" => "Phone",
		"`shippers`.`NumOrders`" => "NumOrders",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`shippers` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 0;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'shippers_view.php';
	$x->RedirectAfterInsert = 'shippers_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Shippers';
	$x->TableIcon = 'resources/table_icons/cart.png';
	$x->PrimaryKey = '`shippers`.`ShipperID`';
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [400, 150, 150, ];
	$x->ColCaption = ['Company Name', 'Phone', 'Number of orders shipped', ];
	$x->ColFieldName = ['CompanyName', 'Phone', 'NumOrders', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/shippers_templateTV.html';
	$x->SelectedTemplate = 'templates/shippers_templateTVS.html';
	$x->TemplateDV = 'templates/shippers_templateDV.html';
	$x->TemplateDVP = 'templates/shippers_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `shippers`.`ShipperID`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='shippers' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `shippers`.`ShipperID`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='shippers' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`shippers`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: shippers_init
	$render = true;
	if(function_exists('shippers_init')) {
		$args = [];
		$render = shippers_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')) {
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])) {
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id) {   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != '') {
				$QueryWhere = 'where `shippers`.`ShipperID` in ('.substr($QueryWhere, 0, -1).')';
			} else { // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		} else {
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery = "SELECT SUM(`shippers`.`NumOrders`) FROM {$x->QueryFrom} {$QueryWhere}";
		$res = sql($sumQuery, $eo);
		if($row = db_fetch_row($res)) {
			$sumRow = '<tr class="success">';
			if(!isset($_REQUEST['Print_x'])) $sumRow .= '<td class="text-center"><strong>&sum;</strong></td>';
			$sumRow .= '<td class="shippers-CompanyName"></td>';
			$sumRow .= '<td class="shippers-Phone"></td>';
			$sumRow .= "<td class=\"shippers-NumOrders text-right\">{$row[0]}</td>";
			$sumRow .= '</tr>';

			$x->HTML = str_replace('<!-- tv data below -->', '', $x->HTML);
			$x->HTML = str_replace('<!-- tv data above -->', $sumRow, $x->HTML);
		}
	}

	// hook: shippers_header
	$headerCode = '';
	if(function_exists('shippers_header')) {
		$args = [];
		$headerCode = shippers_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: shippers_footer
	$footerCode = '';
	if(function_exists('shippers_footer')) {
		$args = [];
		$footerCode = shippers_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
